name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Restore
      run: dotnet restore -bl:logs/restore.binlog

    - name: Build
      run: dotnet build --configuration Debug --no-restore -bl:logs/build.binlog

    - name: Test
      run: dotnet test --configuration Debug --no-build --logger trx --results-directory TestResults

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ./TestResults
      if: ${{ always() }} # Always run this step even on failure

    - name: Upload logs
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: ./logs
      if: ${{ always() }} # Always run this step even on failure
