name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: windows-latest

    env:
      BuildConfiguration: Debug

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: msbuild
